repos:
- repo: https://github.com/kynan/nbstripout
  rev: 0.5.0
  hooks:
    - id: nbstripout

- repo: https://github.com/mwouts/jupytext
  rev: v1.15.1 
  hooks:
    - id: jupytext
      args: [--sync]